import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { slugFromRemoteUrl } from "../server/checkout.ts";
import { noteFileName } from "../server/concepts.ts";
import { isLineInDiff, parseUnifiedDiff } from "../server/diff.ts";
import { tagFile, tagFiles } from "../server/fileTags.ts";
import { checkProof, lineCounterFor } from "../server/proofCheck.ts";
import { findRemovedDeclarations, traceRemovedCode } from "../server/removedCode.ts";
import { extractSection } from "../server/rules.ts";

const SAMPLE_PATCH = `diff --git a/server/order.go b/server/order.go
index 111..222 100644
--- a/server/order.go
+++ b/server/order.go
@@ -1,4 +1,4 @@
 package server
-func validateOrder(order Order) error {
+func checkOrder(order Order) error {
 	return nil
 }
diff --git a/package-lock.json b/package-lock.json
index 333..444 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1 +1 @@
-{}
+{"a":1}
diff --git a/old name.txt b/new name.txt
similarity index 100%
rename from old name.txt
rename to new name.txt
`;

describe("parseUnifiedDiff", () => {
  const files = parseUnifiedDiff(SAMPLE_PATCH);

  it("finds every file with its status", () => {
    expect(files.map((file) => [file.path, file.status])).toEqual([
      ["server/order.go", "modified"],
      ["package-lock.json", "modified"],
      ["new name.txt", "renamed"],
    ]);
  });

  it("numbers old and new lines separately", () => {
    const lines = files[0].hunks[0].lines;
    expect(lines[1]).toEqual({ kind: "del", oldLine: 2, newLine: null, text: "func validateOrder(order Order) error {" });
    expect(lines[2]).toEqual({ kind: "add", oldLine: null, newLine: 2, text: "func checkOrder(order Order) error {" });
    expect(lines[3]).toMatchObject({ kind: "ctx", oldLine: 3, newLine: 3 });
  });

  it("knows which lines a comment can anchor to", () => {
    const [orderFile] = tagFiles(files);
    expect(isLineInDiff(orderFile, 2, "RIGHT")).toBe(true);
    expect(isLineInDiff(orderFile, 2, "LEFT")).toBe(true);
    expect(isLineInDiff(orderFile, 40, "RIGHT")).toBe(false);
  });
});

describe("tagFile", () => {
  const baseFile = { oldPath: "", status: "modified" as const, isBinary: false, hunks: [] };
  const withChange = (text: string) => [{ header: "@@", lines: [{ kind: "add" as const, oldLine: null, newLine: 1, text }] }];

  it("skims tests, lockfiles, generated code, and pure renames", () => {
    expect(tagFile({ ...baseFile, path: "api/order_test.go" }).tagReason).toBe("test");
    expect(tagFile({ ...baseFile, path: "web/src/cart.spec.ts" }).tagReason).toBe("test");
    expect(tagFile({ ...baseFile, path: "go.sum" }).tagReason).toBe("lockfile");
    expect(tagFile({ ...baseFile, path: "proto/cluster.pb.go" }).tagReason).toBe("generated code");
    expect(tagFile({ ...baseFile, path: "a.go", hunks: withChange("// Code generated by protoc. DO NOT EDIT.") }).tag).toBe("skim");
    expect(tagFile({ ...baseFile, path: "b.go", status: "renamed" }).tagReason).toBe("rename only");
  });

  it("marks money, locking, and auth changes as important", () => {
    expect(tagFile({ ...baseFile, path: "a.go", hunks: withChange("s.mu.Lock()") }).tag).toBe("important");
    expect(tagFile({ ...baseFile, path: "payments/refund.go" }).tag).toBe("important");
  });

  it("leaves everything else normal", () => {
    expect(tagFile({ ...baseFile, path: "ui/button.tsx", hunks: withChange("return <div/>") }).tag).toBe("normal");
  });
});

function git(repoDir: string, ...args: string[]): string {
  return execFileSync("git", ["-C", repoDir, ...args], { encoding: "utf8" }).trim();
}

function makeRepoWithRemovedFunction() {
  const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), "review-coach-test-"));
  git(repoDir, "init", "-q");
  git(repoDir, "config", "user.email", "test@example.com");
  git(repoDir, "config", "user.name", "Test");
  fs.writeFileSync(path.join(repoDir, "lib.go"), "package lib\n\nfunc oldHelper() int {\n\treturn 1\n}\n");
  fs.writeFileSync(path.join(repoDir, "main.go"), "package lib\n\nvar value = oldHelper()\n");
  git(repoDir, "add", ".");
  git(repoDir, "commit", "-q", "-m", "Add oldHelper");
  const baseSha = git(repoDir, "rev-parse", "HEAD");
  fs.writeFileSync(path.join(repoDir, "lib.go"), "package lib\n");
  fs.writeFileSync(path.join(repoDir, "main.go"), "package lib\n\nvar value = 1\n");
  git(repoDir, "commit", "-q", "-am", "Drop oldHelper");
  return { repoDir, baseSha, headSha: git(repoDir, "rev-parse", "HEAD") };
}

describe("traceRemovedCode", () => {
  it("shows who used a deleted function before and after", async () => {
    const { repoDir, baseSha, headSha } = makeRepoWithRemovedFunction();
    const patch = git(repoDir, "diff", `${baseSha}...${headSha}`);
    const files = tagFiles(parseUnifiedDiff(patch));
    expect(findRemovedDeclarations(files).map((declaration) => declaration.name)).toEqual(["oldHelper"]);
    const [traced] = await traceRemovedCode(repoDir, files, baseSha, headSha);
    expect(traced.usedBefore).toEqual([{ file: "main.go", line: 3, text: "var value = oldHelper()" }]);
    expect(traced.usedAfter).toEqual([]);
    expect(traced.recentCommits[0].subject).toBe("Add oldHelper");
  });

  it("ignores functions that were only renamed in place", () => {
    const files = tagFiles(parseUnifiedDiff(SAMPLE_PATCH));
    expect(findRemovedDeclarations(files).map((declaration) => declaration.name)).toEqual(["validateOrder"]);
    const renamedBack = SAMPLE_PATCH.replace("+func checkOrder", "+func validateOrder");
    expect(findRemovedDeclarations(tagFiles(parseUnifiedDiff(renamedBack)))).toEqual([]);
  });
});

describe("checkProof", () => {
  it("turns a proven claim with a missing line into a guess", async () => {
    const { repoDir, baseSha } = makeRepoWithRemovedFunction();
    const countLines = lineCounterFor(repoDir, baseSha);
    const proof = { status: "proven" as const, file: "main.go", line: 3, side: "RIGHT" as const, note: "" };
    expect((await checkProof(proof, countLines)).status).toBe("proven");
    expect((await checkProof({ ...proof, line: 99 }, countLines)).status).toBe("guess");
    expect((await checkProof({ ...proof, file: "nope.go" }, countLines)).status).toBe("guess");
    expect((await checkProof({ ...proof, file: "lib.go", line: 4, side: "LEFT" }, countLines)).status).toBe("proven");
  });
});

describe("small helpers", () => {
  it("reads owner and repo from remote URLs", () => {
    expect(slugFromRemoteUrl("git@github.com:Round2POS/crm.git")).toBe("round2pos/crm");
    expect(slugFromRemoteUrl("https://github.com/Round2POS/device-manager")).toBe("round2pos/device-manager");
  });

  it("extracts one markdown section", () => {
    const markdown = "# One\na\n# Two — rule\nb\nc\n# Three\nd";
    expect(extractSection(markdown, "# Two")).toBe("# Two — rule\nb\nc");
  });

  it("keeps slashes out of note names", () => {
    expect(noteFileName("Lock/unlock: mutex")).toBe("Lock unlock mutex.md");
  });
});
